### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eltair** [tml1024/flying-brick#4]
There's surprising amount of code for such a simple flight model. I would love to see some high level documentation about the strategy/architecture for accomplishing this. I think it would make it a lot easier to dive into the code as a newbie.

Thanks,
Matt

**Comment by tml1024** [comment]
Well, the intent is that the code can be used as a basis for more interesting and complicated flight models, so I tried to make it easy to extend. But of course, patches welcome.
