### ISSUE TITLE
Where is the MSFS flight model overridden ?

### ISSUE THREAD

**Issue by fyyyyy** [tml1024/flying-brick#5]
Hello
I can see the flying-brick-main\Sources\Code, but how is MSFS instructed to use this flight model ?

I want to apply this flight model to an existing MSFS aircraft but i'm not sure how this can be achieved. 

Thanks

**Comment by tml1024** [comment]
_> how is MSFS instructed to use this flight model_

It isn't. There C++ code in there *is* the "flight model". The code tells MSFS what the velocity of the aircraft is at each time it is called (multiple times per second).

_> I want to apply this flight model to an existing MSFS aircraft_

Probably not going to work. Especially not if it is one of the aircraft distributed in the in-game Marketplace which have encrypted contents. But for some distributed as a zip file on other sites, you could try to modify it's panel.cfg to get your own WASM module to run for some dummy panel. But then you would need to add a texture panel to the 3D model of the aircraft, too. (Look for the small rectangle with the texture $Screen_1 in the Fuselage of the Flying Brick. That is referenced in its panel.cfg.)

--tml

**Comment by tml1024** [comment]
(This is not really an issue.)
